### ISSUE TITLE
Asset Workflow State

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-ui-bundle#226]
![image](https://github.com/pimcore/studio-ui-bundle/assets/8792145/b4b874a1-3759-461b-a6f2-fc0d1129626e)

**Comment by markus-moser** [comment]
**@studio-backend-team**

In addition to the already provided workflow actions in the API we will need some more details:

* In the workflow places config we have a attribute `visibleInHeader`. We will need this to identify which places should be shown next to the transitions button: 
![Image](https://github.com/pimcore/studio-ui-bundle/assets/4639428/d19141fc-e260-4fe6-a284-b1386863dc71)
I think it is fine when we just add this to the existing `/studio/api/workflows/details` endpoint. `visibleInHeader` is not the best name anymore because it is not shown in the header anymore. But let's keep it at least for the moment. We can think about changing it in the workflow engine in the next major version(s) of pimcore/pimcore.

* In the asset detail API we should add a boolean indicator if a workflow is available. This would avoid calling the workflow detail API all the time for entities without any workflow.

* For the `notes` within a transition or global action you implemnted already `commentEnabled` and `commentRequired` attributes. We will need also the `additionalFields` (with the sub attributes `name`, `fieldType`, `title`, `required` and `fieldTypeSettings`) there. 

* Don't know if this is already respected but for the `/studio/api/workflows/action` endpoint we will also need to respect the various options like comment and additional fields.

**Comment by lukmzig** [comment]
@markus-moser 
- for the first point we added `visibleInDetail` [parameter](https://github.com/pimcore/studio-backend-bundle/blob/1.x/src/Workflow/Schema/WorkflowStatus.php#L62) which reflects the `visibleInHeader` value
- boolean indicator if a workflow is available - would it be possible to add this parameter into the GDI? That would be somehow the fastest solution for now since our detail API now delivers only data from the GDI.

**Comment by lukmzig** [comment]
> * boolean indicator if a workflow is available - would it be possible to add this parameter into the GDI? That would be somehow the fastest solution for now since our detail API now delivers only data from the GDI.

Would this be possible @markus-moser? :)

**Comment by markus-moser** [comment]
@lukmzig Sorry for the late reply. Unfortunately this will not work correctly as there could be also expressions in the supports strategy involved like here:

https://github.com/pimcore/demo-enterprise/blob/2024.x/var/config/workflow-designer/workflows.yaml#L91

So it might be that it is dependent on the logged in user and not the same for all users.

**Comment by lukmzig** [comment]
We need to switch the detail endpoint to load the Asset from the DB ( in the future for example also because of drafts) and check permissions using GDI. 

Furthermore add:
In the asset detail API we should add a boolean indicator if a workflow is available. This would avoid calling the workflow detail API all the time for entities without any workflow.

**Comment by lukmzig** [comment]
@markus-moser new property indicating the workflow availability was added to the detail endpoints
