### ISSUE TITLE
[Schedule] Centralized date formatting service

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-ui-bundle#365]
I created a similar issue also for the version view: #356 

We should ensure that we have the same date formats everywhere and put the date/time/number formatting to centralized services which are re-used everywhere.

Related to #348

**Comment by Corepex** [comment]
I already started with that. 
https://github.com/pimcore/studio-ui-bundle/blob/1.x/assets/js/src/core/app/config/date-time.tsx

There would be the place to configure everything. 

**BUT:** We should question us if its really necessary to have a date / time formatted since this is already handled by i18n.
See: https://github.com/pimcore/studio-ui-bundle/blob/1bb82a2cf76c352a9f514e58868b80928a5939cf/assets/js/src/core/components/formatted-date/formatted-date.tsx#L23-L27 or https://github.com/pimcore/studio-ui-bundle/blob/1bb82a2cf76c352a9f514e58868b80928a5939cf/assets/js/src/core/components/formatted-time/formatted-time.tsx#L23-L30

**Comment by markus-moser** [comment]
@Corepex Please create centralized utils as wrapper of I18N to format dates
