### ISSUE TITLE
migrate to svelte

### ISSUE THREAD

**Issue by nosovk** [pimcore/studio-ui-bundle#508]
Actually just find out that our favourite PIMCore going to rollout new version of Admin UI, and it will be based on React. Unfortunately I've missed community discussion regarding such a decision, but would suggest to migrate to something like [Svelte](https://svelte.dev/) or at least Vue, to improve learning curve for new developers. It's much easier to fix something in Svelte templates for any PHP developer familiar with Twig, rather then master react components.
It should be possible, till we dont make a final release.

**Comment by dpfaffenbauer** [comment]
there wasn't any discussion about this. 

Regarding migrating to vue or svelte because of the learning curve: this is a very biased statement. we (as pimcore partner and agency) have used vue and react and are happy with both of them. react is more widely used with a much bigger community. 

in the end, it is Pimcore's decision and they decided to use react. Which is fine.

**Comment by fashxp** [comment]
Hi, 
some discussion was going on [here](https://github.com/orgs/pimcore/discussions/12795) and also on our inspire conference. 
Here you also find a [video](https://youtu.be/hnOdy5dC88A?list=PLrlLr70ddFwI2jmKOHrnsLyZwUUZ-A4pm&t=1268) with some additional reasoning why we decided to do things the way we did. 


> react is more widely used with a much bigger community

These were actually some of the reasons why we went for react. And we will stick to that decision and cannot move to another technology anymore...
